---
#- name: GRAB F5 FACTS
#  hosts: all
#  gather_facts: false
#
#  collections:
#    - f5networks.f5_modules
#  tasks:
#    - name: COLLECT BIG-IP FACTS
#      bigip_device_info:
#        gather_subset:
#          - system-info
#        hostname: 192.168.221.133
#        provider:
#          server: "{{private_ip}}"
#          user: "{{ansible_user}}"
#          password: "{{ansible_ssh_pass}}"
#          validate_certs: false
#      register: device_facts
#
#    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
#      debug:
#        var: device_facts

- name: Set the hostname of the BIG-IP
  bigip_hostname:
    hostname: 192.168.221.133
    provider:
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server: "{{private_ip}}"
